build:
    echo "Construct the application."

run:
    echo "Start the application."

test:
    echo "Test the application."

release:
    echo "Make sure the application is ready to be released."

clean:
    echo "Clean up the application code."

all:
    echo "Hello World"

default:
    echo "Hello World"
